/* MovieBlog homepage — live trends + latest regional discovery + live editorial + OTT */
(() => {
  const IMAGE_BASE='https://image.tmdb.org/t/p/w500';
  const grid=document.getElementById('movieGrid'),loading=document.getElementById('loading'),cardTemplate=document.getElementById('cardTemplate'),trendFeed=document.getElementById('trendFeed'),viralFeed=document.getElementById('viralFeed'),buzzFeed=document.getElementById('buzzFeed'),watchFeed=document.getElementById('watchFeed'),dailyDate=document.getElementById('dailyDate');
  if(!grid)return;
  const favoritesKey='movieblog:favorites:v3';let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem(favoritesKey)||'[]'))}catch(_){ }
  const normalize=movie=>({...movie,id:movie.id||`${movie.title||'movie'}-${movie.release_date||''}`,title:movie.title||movie.name||'Untitled',poster:movie.poster||(movie.poster_path?IMAGE_BASE+movie.poster_path:''),overview:movie.overview||'',releaseDate:String(movie.releaseDate||movie.release_date||''),rating:Number(movie.rating||movie.vote_average||0)});
  const esc=value=>String(value||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const movieUrl=id=>`./pages/movie?id=${encodeURIComponent(id)}`;
  const badTrend=/football|soccer|cricket|tennis|psg|lens vs|playstation|sports|olympics|formula 1|\bnba\b|\bnfl\b|election|politics|minister|parliament|court|police|crime|weather|rain forecast|stock market|share price|gold price|fuel price|hospital|disease|medical|exam result/i;
  const entertainment=/movie|film|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime video|jiohotstar|hotstar|zee5|sony liv|series|web series|box office|theatrical|release|director|producer|song|music|singer|album|episode|season|fans|viral|gossip|rumou?r|dating|relationship|marriage|breakup|engagement|wedding|feud/i;
  const api=async url=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),9000);try{const response=await fetch(url,{cache:'no-store',signal:controller.signal});if(!response.ok)throw new Error(`Request failed: ${response.status}`);return response.json()}finally{clearTimeout(timer)}};
  function renderMovieCards(items){grid.querySelectorAll('.card').forEach(node=>node.remove());loading.style.display=items.length?'none':'block';if(!items.length){loading.textContent='No recent movies available right now.';return}const fragment=document.createDocumentFragment();items.slice(0,8).map(normalize).forEach(movie=>{const tpl=cardTemplate.content.cloneNode(true),article=tpl.querySelector('article'),img=tpl.querySelector('.poster'),title=tpl.querySelector('.title'),meta=tpl.querySelector('.meta'),overview=tpl.querySelector('.overview'),fav=tpl.querySelector('.fav-toggle');article.dataset.id=movie.id;img.src=movie.poster||'./assets/placeholder.png';img.alt=`${movie.title} poster`;title.textContent=movie.title;meta.textContent=`${movie.releaseDate?movie.releaseDate.slice(0,4):'TBA'} · ⭐ ${movie.rating?movie.rating.toFixed(1):'—'}`;overview.textContent=movie.overview;if(favorites.has(String(movie.id))){fav.textContent='♥';fav.setAttribute('aria-pressed','true')}fav.addEventListener('click',event=>{event.stopPropagation();const id=String(movie.id);if(favorites.has(id)){favorites.delete(id);fav.textContent='♡';fav.setAttribute('aria-pressed','false')}else{favorites.add(id);fav.textContent='♥';fav.setAttribute('aria-pressed','true')}localStorage.setItem(favoritesKey,JSON.stringify([...favorites]))});const open=()=>{window.location.href=movieUrl(movie.id)};article.addEventListener('click',open);article.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}});fragment.appendChild(tpl)});grid.insertBefore(fragment,loading)}
  async function loadRegional(language){try{const data=await api(`./api/tmdb?mode=regional&original_language=${encodeURIComponent(language)}&region=IN&language=en-US&page=1`);renderMovieCards(Array.isArray(data.results)?data.results:[])}catch(_){loading.style.display='block';loading.textContent='Recent movie data is temporarily unavailable.'}}
  function storyItem(item,index,label,url){return `<article class="story-item"><div class="story-number">${String(index+1).padStart(2,'0')}</div><div><a href="${esc(url||item.url||`./pages/trending?topic=${encodeURIComponent(item.title||'')}`)}" target="_blank" rel="noopener noreferrer"><h3>${esc(item.title)}</h3></a><p><strong>${esc(label)}</strong> · ${esc(item.description||'Latest entertainment report from the source.')}</p><small class="source-note">${esc(item.source||item.newsSources?.[0]||'Source report')}</small></div></article>`}
  function renderTrends(items,fallbackNews=[]){
    let rows=(items||[]).filter(x=>(x.relevance==='high'||x.relevance==='medium')&&!badTrend.test(`${x.title} ${x.description||''} ${(x.newsTitles||[]).join(' ')}`)).slice(0,6);
    if(!rows.length){
      rows=(fallbackNews||[]).filter(x=>entertainment.test(`${x.title||''} ${x.description||''} ${x.source||''}`)&&!badTrend.test(`${x.title||''} ${x.description||''}`)).slice(0,6).map((x,i)=>({...x,score:null,bucket:'trending',fallback:true}));
    }
    trendFeed.innerHTML=rows.length?rows.map((item,i)=>`<a class="trend-item" href="./pages/trending?topic=${encodeURIComponent(item.title||'')}"><span class="trend-rank">${String(i+1).padStart(2,'0')}</span><span class="trend-item-body"><strong class="trend-title">${esc(item.title)}</strong><small class="trend-meta">${esc(item.newsSources?.[0]||item.source||'Entertainment source')} · ${esc(item.bucket==='buzz'?'Buzz':item.bucket==='viral'?'Viral':'Trending')} · ${item.score!=null?`${Number(item.score||0)} pulse`:'Current'}</small></span><strong class="trend-score">${item.score!=null?`${Number(item.score||0)} Pulse`:'Live'}</strong></a>`).join(''):'<div class="loading">No current entertainment trend is available from the latest source scan.</div>';
  }
  function renderBuzz(items){if(!buzzFeed)return;const rows=items.filter(x=>!badTrend.test(`${x.title} ${x.description||''}`)).slice(0,4);buzzFeed.innerHTML=rows.length?rows.map((item,i)=>storyItem(item,i,/official|confirmed|statement|announced/i.test(`${item.title} ${item.description}`)?'Confirmed / reported':'Rumour / buzz',item.url)).join(''):'<div class="mini-item"><span>Public buzz</span><h3>No current celebrity or movie rumour passed the source check.</h3></div>'}
  function renderNews(items){const root=document.getElementById('editorialFeed');if(!root)return;const rows=items.filter(x=>!badTrend.test(`${x.title} ${x.description||''}`)).slice(0,6);root.innerHTML=rows.length?rows.map((item,i)=>storyItem(item,i,/official|confirmed|announced|statement|revealed/i.test(`${item.title} ${item.description}`)?'Confirmed / reported':'Cinema update',item.url)).join(''):'<p class="muted">No fresh cinema reports were found in the latest source scan.</p>'}
  function renderViral(news,trends){if(!viralFeed)return;let rows=news.filter(x=>/viral|meme|internet|social media|instagram|youtube|reaction|views|fans/i.test(`${x.title} ${x.description}`)).slice(0,5);if(!rows.length)rows=trends.filter(x=>/viral|meme|internet|social media|reaction|views|fans/i.test(`${x.title} ${x.description||''} ${(x.newsTitles||[]).join(' ')}`)).slice(0,5);viralFeed.innerHTML=rows.length?rows.map((item,i)=>storyItem(item,i,'Viral cinema',item.url||item.newsUrls?.[0])).join(''):'<div class="loading">No strong entertainment viral signal is available right now.</div>'}
  async function loadLive(){
    const [trendResult,newsResult,gossipResult]=await Promise.allSettled([api('./api/trends'),api('./api/editorial?type=news'),api('./api/editorial?type=buzz')]);
    const trendData=trendResult.status==='fulfilled'?trendResult.value:{trends:[]};
    const newsData=newsResult.status==='fulfilled'?newsResult.value:{items:[]};
    const gossipData=gossipResult.status==='fulfilled'?gossipResult.value:{items:[]};
    const trends=Array.isArray(trendData.trends)?trendData.trends:[];
    const news=Array.isArray(newsData.items)?newsData.items:[];
    const gossip=Array.isArray(gossipData.items)?gossipData.items:[];
    renderTrends(trends,news);
    renderNews(news);
    renderBuzz(gossip);
    renderViral(news,trends);
  }
  function renderWatch(items){const movies=items.slice(0,5).map(normalize);if(!movies.length){watchFeed.innerHTML='<div class="loading">OTT picks are being refreshed.</div>';return}watchFeed.innerHTML=movies.map(movie=>{const providers=Array.isArray(movie.providers)&&movie.providers.length?movie.providers.join(' · '):'Streaming availability in India';return `<article class="watch-card"><a href="${movieUrl(movie.id)}"><img loading="lazy" src="${movie.poster||'./assets/placeholder.png'}" alt="${esc(movie.title)} poster"></a><div class="watch-body"><span class="watch-tag">Worth watching</span><h3><a href="${movieUrl(movie.id)}">${esc(movie.title)}</a></h3><p>⭐ ${movie.rating?movie.rating.toFixed(1):'—'} · ${esc(providers)}</p></div></article>`}).join('')}
  function renderNewOtt(items){const strip=document.querySelector('.utility-strip');if(!strip)return;const movies=items.slice(0,3).map(normalize);strip.innerHTML=movies.length?movies.map(movie=>`<div><strong>${esc(movie.title)}</strong><span>${movie.releaseDate?new Date(movie.releaseDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'Recently released'} · New on OTT</span></div>`).join(''):'<div><strong>No new OTT releases found</strong><span>India streaming data is being refreshed.</span></div>'}
  async function loadWatch(){try{const data=await api('./api/tmdb?mode=streaming&region=IN&language=en-US&page=1');renderWatch(Array.isArray(data.results)?data.results:[])}catch(_){watchFeed.innerHTML='<div class="loading">OTT recommendations are temporarily unavailable.</div>'}}
  async function loadNewOtt(){try{const data=await api('./api/tmdb?mode=streaming_new&region=IN&language=en-US&page=1');renderNewOtt(Array.isArray(data.results)?data.results:[])}catch(_){}}
  function setDate(){if(dailyDate)dailyDate.textContent=new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date())}
  document.querySelectorAll('.region-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.region-tab').forEach(other=>{other.classList.remove('is-active');other.setAttribute('aria-selected','false')});tab.classList.add('is-active');tab.setAttribute('aria-selected','true');loadRegional(tab.dataset.region)}));setDate();loadRegional('te');loadLive();loadWatch();loadNewOtt();
})();
