const FEEDS={buzz:[['Google News · Bollywood','Bollywood celebrity gossip OR rumour OR controversy when:1d'],['Google News · Tollywood','Tollywood celebrity gossip OR rumour OR controversy when:1d'],['Google News · South Cinema','South Indian cinema celebrity gossip OR rumour OR controversy when:1d'],['Google News · Entertainment India','Indian film celebrity gossip OR rumour OR relationship when:1d']],boxoffice:[['Google News · India Box Office','Indian movie box office collection OR earnings OR opening when:3d'],['Google News · Telugu Box Office','Telugu movie box office collection OR earnings OR opening when:3d'],['Google News · Hindi Box Office','Bollywood box office collection OR earnings OR opening when:3d'],['Google News · Tamil Box Office','Tamil movie box office collection OR earnings OR opening when:3d'],['Google News · Malayalam Box Office','Malayalam movie box office collection OR earnings OR opening when:3d'],['Google News · Kannada Box Office','Kannada movie box office collection OR earnings OR opening when:3d']],news:[['Google News · Indian Cinema','Indian cinema movie actor trailer OTT when:1d'],['Google News · Telugu Cinema','Telugu cinema movie news when:1d'],['Google News · Bollywood','Bollywood movie news when:1d']]};
const CACHE=new Map(),TTL=600000;
function decode(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'")}
function tag(b,n){const m=b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)</${n}>`,'i'));return m?decode(m[1].trim()):''}
function allTags(b,n){return[...b.matchAll(new RegExp(`<${n}[^>]*>([\\s\\S]*?)</${n}>`,'gi'))].map(m=>decode(m[1].trim())).filter(Boolean)}
function strip(s){return decode(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function items(xml,feedSource){return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:strip(tag(b,'title')),description:strip(tag(b,'description')),url:tag(b,'link'),pubDate:tag(b,'pubDate'),source:strip(tag(b,'source'))||feedSource,newsTitles:allTags(b,'ht:news_item_title')})).filter(x=>x.title&&x.url)}
function rss(q){return`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`}
async function feed(source,q){const r=await fetch(rss(q),{headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)throw Error(`${source} ${r.status}`);return items(await r.text(),source)}
function unique(a){const s=new Set();return a.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9]+/g,' ');if(s.has(k))return false;s.add(k);return true})}
function buzzScore(x){const s=`${x.title} ${x.description}`.toLowerCase();return 20+(/official|confirmed|statement|announced/.test(s)?12:0)+(/rumou?r|speculation|reportedly|alleged|dating|affair|breakup|wedding|spotted|controversy|feud/.test(s)?25:0)+(/viral|fans|social media|internet/.test(s)?15:0)}
function boxScore(x){const s=`${x.title} ${x.description}`.toLowerCase();return 20+(/day \d+|opening|weekend|collection|crore|cr|million|earnings|gross|net/.test(s)?30:0)+(/hit|blockbuster|success|super hit|strong|surpasses|crosses/.test(s)?20:0)+(/flop|disaster|underperform|weak|crash|fails/.test(s)?18:0)}
function verdict(x){const s=`${x.title} ${x.description}`.toLowerCase();if(/blockbuster|super hit|success|big hit/.test(s))return'Hit / strong performance';if(/flop|disaster|underperform|poor|fails/.test(s))return'Underperforming';if(/mixed|average|steady|decent/.test(s))return'Mixed / steady';return'Early performance'}
function money(x){const s=`${x.title} ${x.description}`;const m=s.match(/(?:₹|rs\.?|inr\s*)\s*([\d,.]+)\s*(crore|cr|million|lakh)?/i);return m?`₹${m[1]}${m[2]?' '+m[2]:''}`:''}
async function trendingMovieQueries(){try{const r=await fetch('https://trends.google.com/trending/rss?geo=IN',{headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)return[];const rows=items(await r.text(),'Google Trends');const terms=['movie','film','cinema','trailer','teaser','actor','actress','celebrity','bollywood','tollywood','kollywood','mollywood','hollywood','ott','series','box office','release','star cast','director','producer','marvel','spider-man','spiderman','netflix','prime video','jiohotstar'];const bad=['football','soccer','cricket','tennis','psg','lens vs','playstation','sports','olympics','formula 1','f1','nba','nfl','election','politics','weather','rain','stock market','share price','gold price','fuel price','hospital','disease','crime','police'];return rows.filter(x=>{const s=`${x.title} ${x.description} ${(x.newsTitles||[]).join(' ')}`.toLowerCase();return terms.some(t=>s.includes(t))&&!bad.some(t=>s.includes(t))}).slice(0,8).map(x=>x.title)}catch(_){return[]}}
async function recentMovieQueries(apiKey){if(!apiKey)return[];try{const url=`https://api.themoviedb.org/3/movie/now_playing?api_key=${encodeURIComponent(apiKey)}&language=en-US&region=IN&page=1`;const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)return[];const d=await r.json();return(Array.isArray(d.results)?d.results:[]).filter(x=>x.title).slice(0,12).map(x=>x.title)}catch(_){return[]}}
async function collect(type,query){let feeds=FEEDS[type]||FEEDS.news;if(query){const clean=query.replace(/["']/g,'').trim();feeds=[[`Google News · ${clean}`,`"${clean}" box office collection OR earnings OR opening OR day when:7d`],[`Google News · ${clean} broad`,` ${clean} movie box office OR collection OR earnings when:7d`]]}const settled=await Promise.allSettled(feeds.map(f=>feed(f[0],f[1])));let rows=unique(settled.flatMap(r=>r.status==='fulfilled'?r.value:[]));rows=rows.filter(x=>{const s=`${x.title} ${x.description}`.toLowerCase();if(type==='buzz')return/gossip|rumou?r|controvers|dating|relationship|marriage|breakup|spotted|affair|feud|viral|statement|reportedly/.test(s);if(type==='boxoffice')return/box office|collection|crore|opening|day \d+|weekend|hit|flop|disaster|underperform|earnings|worldwide|domestic|gross|net/.test(s);return/movie|film|cinema|actor|actress|celebrity|ott|trailer|teaser|series|streaming/.test(s)});rows.sort((a,b)=>type==='buzz'?buzzScore(b)-buzzScore(a):type==='boxoffice'?boxScore(b)-boxScore(a):new Date(b.pubDate)-new Date(a.pubDate));return rows}
export async function onRequestGet(context){const u=new URL(context.request.url),requested=u.searchParams.get('type')||'news',type=['buzz','boxoffice','news','boxoffice_trending'].includes(requested)?requested:'news',query=(u.searchParams.get('q')||'').trim().slice(0,80),key=`${type}:${query}`,cached=CACHE.get(key);if(cached&&Date.now()-cached.time<TTL)return new Response(JSON.stringify(cached.data),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=600'}});try{let rows=[];let trendTitles=[];if(type==='boxoffice_trending'){const [trendTitlesRaw,recentTitles]=await Promise.all([trendingMovieQueries(),recentMovieQueries(context.env?.TMDB_API_KEY)]);trendTitles=unique([...trendTitlesRaw,...recentTitles].map(title=>({title}))).map(x=>x.title);const batches=await Promise.allSettled(trendTitles.slice(0,10).map(title=>collect('boxoffice',title)));rows=unique(batches.flatMap(r=>r.status==='fulfilled'?r.value:[]));if(!rows.length)rows=await collect('boxoffice','');}else rows=await collect(type,query);const data={type,query,fetchedAt:new Date().toISOString(),trendingMovies:trendTitles,items:rows.slice(0,24).map(x=>({...x,verdict:type.startsWith('boxoffice')?verdict(x):null,amount:type.startsWith('boxoffice')?money(x):null}))};CACHE.set(key,{time:Date.now(),data});return new Response(JSON.stringify(data),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=600, stale-while-revalidate=1800'}})}catch(_){return new Response(JSON.stringify({type,query,fetchedAt:new Date().toISOString(),trendingMovies:[],items:[],error:'Live entertainment sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300'}})}}
