const FEEDS={buzz:[['Google News · Bollywood','Bollywood celebrity gossip OR rumour OR controversy when:1d'],['Google News · Tollywood','Tollywood celebrity gossip OR rumour OR controversy when:1d'],['Google News · South Cinema','South Indian cinema celebrity gossip OR rumour OR controversy when:1d'],['Google News · Entertainment India','Indian film celebrity gossip OR rumour OR relationship when:1d']],boxoffice:[['Google News · India Box Office','Indian movie box office collection when:2d'],['Google News · Telugu Box Office','Telugu movie box office collection when:2d'],['Google News · Hindi Box Office','Bollywood box office collection when:2d'],['Google News · Tamil Box Office','Tamil movie box office collection when:2d'],['Google News · Malayalam Box Office','Malayalam movie box office collection when:2d'],['Google News · Kannada Box Office','Kannada movie box office collection when:2d']],news:[['Google News · Indian Cinema','Indian cinema movie actor trailer OTT when:1d'],['Google News · Telugu Cinema','Telugu cinema movie news when:1d'],['Google News · Bollywood','Bollywood movie news when:1d']]};
const CACHE=new Map(),TTL=600000;
function decode(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'")}
function tag(b,n){const m=b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)</${n}>`,'i'));return m?decode(m[1].trim()):''}
function strip(s){return decode(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function items(xml,feedSource){return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:strip(tag(b,'title')),description:strip(tag(b,'description')),url:tag(b,'link'),pubDate:tag(b,'pubDate'),source:strip(tag(b,'source'))||feedSource})).filter(x=>x.title&&x.url)}
function rss(q){return`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`}
async function feed(source,q){const r=await fetch(rss(q),{headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)throw Error(`${source} ${r.status}`);return items(await r.text(),source)}
function unique(a){const s=new Set();return a.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9]+/g,' ');if(s.has(k))return false;s.add(k);return true})}
function buzzScore(x){const s=`${x.title} ${x.description}`.toLowerCase();return 20+(/official|confirmed|statement|announced/.test(s)?12:0)+(/rumou?r|speculation|reportedly|alleged|dating|affair|breakup|wedding|spotted|controversy|feud/.test(s)?25:0)+(/viral|fans|social media|internet/.test(s)?15:0)}
function boxScore(x){const s=`${x.title} ${x.description}`.toLowerCase();return 20+(/day \d+|opening|weekend|collection|crore|cr|million/.test(s)?30:0)+(/hit|blockbuster|success|super hit|strong|surpasses|crosses/.test(s)?20:0)+(/flop|disaster|underperform|weak|crash|fails/.test(s)?18:0)}
function verdict(x){const s=`${x.title} ${x.description}`.toLowerCase();if(/blockbuster|super hit|success|big hit/.test(s))return'Hit / strong performance';if(/flop|disaster|underperform|poor|fails/.test(s))return'Underperforming';if(/mixed|average|steady|decent/.test(s))return'Mixed / steady';return'Early performance'}
function money(x){const m=`${x.title} ${x.description}`.match(/(?:rs\.?|₹)\s?([\d,.]+)\s?(crore|cr|million)?/i);return m?`₹${m[1]}${m[2]?' '+m[2]:''}`:''}
export async function onRequestGet(context){const u=new URL(context.request.url),type=['buzz','boxoffice','news'].includes(u.searchParams.get('type'))?u.searchParams.get('type'):'news',query=(u.searchParams.get('q')||'').trim().slice(0,80),key=`${type}:${query}`,cached=CACHE.get(key);if(cached&&Date.now()-cached.time<TTL)return new Response(JSON.stringify(cached.data),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=600'}});try{let feeds=FEEDS[type];if(query)feeds=[[`Google News · ${query}`,`${query} ${type==='boxoffice'?'box office collection':type==='buzz'?'gossip OR rumour OR controversy':'movie news'} when:3d`]];const settled=await Promise.allSettled(feeds.map(f=>feed(f[0],f[1])));let rows=unique(settled.flatMap(r=>r.status==='fulfilled'?r.value:[]));rows=rows.filter(x=>{const s=`${x.title} ${x.description}`.toLowerCase();if(type==='buzz')return/gossip|rumou?r|controvers|dating|relationship|marriage|breakup|spotted|affair|feud|viral|statement|reportedly/.test(s);if(type==='boxoffice')return/box office|collection|crore|opening|day \d+|weekend|hit|flop|disaster|underperform/.test(s);return true});rows.sort((a,b)=>type==='buzz'?buzzScore(b)-buzzScore(a):type==='boxoffice'?boxScore(b)-boxScore(a):new Date(b.pubDate)-new Date(a.pubDate));const data={type,query,fetchedAt:new Date().toISOString(),items:rows.slice(0,24).map(x=>({...x,verdict:type==='boxoffice'?verdict(x):null,amount:type==='boxoffice'?money(x):null}))};CACHE.set(key,{time:Date.now(),data});return new Response(JSON.stringify(data),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=600, stale-while-revalidate=1800'}})}catch(_){return new Response(JSON.stringify({type,query,fetchedAt:new Date().toISOString(),items:[],error:'Live entertainment sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300'}})}}
