const BASE='https://news.google.com/rss/search';
const HEADERS={accept:'application/rss+xml, application/xml, text/xml'};
const NEWS_QUERIES=['Indian cinema movie Telugu Bollywood Tamil Malayalam Kannada Hollywood','Tollywood Telugu movie news actor actress trailer release','Bollywood movie news actor actress trailer release','Indian celebrity entertainment gossip rumour relationship movie','OTT Netflix Prime Video JioHotstar Zee5 SonyLIV Indian movies series','Indian movie box office collections Telugu Bollywood Tamil Malayalam Kannada'];
const decode=v=>String(v||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const strip=v=>decode(String(v||'').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();
const tag=(b,n)=>{const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)</${n}>`,'i'));return m?strip(m[1]):''};
function parse(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),url:tag(b,'link'),description:strip(tag(b,'description')),pubDate:tag(b,'pubDate'),source:tag(b,'source')})).filter(x=>x.title&&x.url)}
const entertainment=/movie|movies|film|films|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime video|jiohotstar|hotstar|zee5|sony liv|series|web series|box office|theatrical|release|director|producer|song|music|singer|album|episode|season|fans|viral|gossip|rumou?r|dating|relationship|marriage|breakup|engagement|wedding|feud/i;
const nonEntertainment=/football|soccer|cricket|tennis|psg|playstation|sports|election|politics|minister|parliament|weather|rain forecast|stock market|share price|gold price|fuel price|bank|hospital|disease|crime|police|exam result/i;
function keep(x){const s=`${x.title} ${x.description} ${x.source}`;return entertainment.test(s)&&!nonEntertainment.test(s)}
function classify(x){const s=`${x.title} ${x.description}`;if(/official|confirmed|announced|statement|revealed|released/i.test(s))return'confirmed';if(/rumou?r|reportedly|speculation|dating|relationship|marriage|breakup|engagement|spotted|affair|feud/i.test(s))return'rumour';if(/viral|meme|internet|social media|instagram|youtube|reaction|views|fans/i.test(s))return'viral';return'explained'}
function amount(text){const s=String(text||'');const m=s.match(/(?:₹|rs\.?|inr)\s?[\d,.]+\s?(?:crore|cr|lakh|million)?/i)||s.match(/[\d,.]+\s?(?:crore|cr|lakh)\s?(?:worldwide|ww|india|net)?/i);return m?m[0].replace(/\s+/g,' ').trim():''}
function verdict(text){const s=String(text||'').toLowerCase();if(/blockbuster|all[- ]time blockbuster/.test(s))return'Source-reported: Blockbuster';if(/super hit|superhit/.test(s))return'Source-reported: Super Hit';if(/\bhit\b/.test(s))return'Source-reported: Hit';if(/success|successful|successful run/.test(s))return'Source-reported: Success';if(/average/.test(s))return'Source-reported: Average';if(/flop|disaster/.test(s))return'Source-reported: '+(s.includes('disaster')?'Disaster':'Flop');return'Collection report'}
async function fetchQuery(q){const url=`${BASE}?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`;const r=await fetch(url,{headers:HEADERS});if(!r.ok)throw new Error(`News RSS ${r.status}`);return parse(await r.text())}
export async function onRequestGet({request}){const u=new URL(request.url);const type=u.searchParams.get('type')||'news';const q=u.searchParams.get('q')?.trim()||'';let queries=NEWS_QUERIES;if(type==='boxoffice')queries=q?[`"${q}" box office collections`,`"${q}" box office verdict`,`"${q}" theatrical collections`]:['Indian movie box office collections today','Telugu movie box office collections today','Bollywood movie box office collections today'];if(type==='gossip')queries=['Indian celebrity gossip rumours today','Tollywood gossip rumours today','Bollywood celebrity gossip today','South Indian cinema gossip today'];if(type==='ott')queries=['new OTT releases India today movies series','Netflix Prime Video JioHotstar new releases India','Indian movies streaming this week'];try{const batches=await Promise.all(queries.map(fetchQuery));let items=batches.flat().filter(keep);const seen=new Set();items=items.filter(x=>{const key=x.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>new Date(b.pubDate||0)-new Date(a.pubDate||0));if(type==='gossip')items=items.filter(x=>classify(x)==='rumour'||/gossip|rumou?r|dating|relationship|marriage|breakup|feud/i.test(`${x.title} ${x.description}`));if(type==='boxoffice')items=items.map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}));return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),items:items.slice(0,30)}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}catch(e){return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),items:[],error:'Live entertainment sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}}
