const BASE='https://news.google.com/rss/search';
const HEADERS={accept:'application/rss+xml, application/xml, text/xml'};
const NEWS_QUERIES=['Indian cinema movie Telugu Bollywood Tamil Malayalam Kannada Hollywood','Tollywood Telugu movie news actor actress trailer release','Bollywood movie news actor actress trailer release','Indian celebrity entertainment gossip rumour relationship movie','OTT Netflix Prime Video JioHotstar Zee5 SonyLIV Indian movies series','Indian movie box office collections Telugu Bollywood Tamil Malayalam Kannada'];
const DEFAULT_BOXOFFICE_MOVIES=['Vishwanath and Sons','DC','Thudakkam','Korean Kanakaraju','Awarapan 2','Batwara 1947','Magudam','Spider-Man: Brand New Day'];
const FALLBACK_BOX=[
 {title:'Vishwanath and Sons crosses ₹100 crore worldwide in two days',movieTitle:'Vishwanath and Sons',amount:'₹100+ Cr worldwide (Day 2)',verdict:'Source-reported: Success',url:'https://timesofindia.indiatimes.com/entertainment/tamil/movies/news/suriya-and-mamitha-baiju-starrer-vishwanath-and-sons-crosses-rs-100-crore-worldwide-in-just-two-days/articleshow/133274258.cms',description:'Suriya and Mamitha Baiju starrer crosses the ₹100 crore worldwide milestone in two days.',source:'Times of India',pubDate:'2026-08-17'},
 {title:'Awarapan 2 enters the ₹50 crore India club in two days',movieTitle:'Awarapan 2',amount:'₹50+ Cr India (Day 2)',verdict:'Source-reported: Strong opening',url:'https://m.economictimes.com/magazines/panache/awarapan-2-box-office-collection-day-2-emraan-hashmis-sequel-beats-batwara-1947-enters-rs-50-crore-club-in-india-awarapan-3-update/articleshow/133268852.cms',description:'Awarapan 2 posts a strong opening and crosses ₹50 crore in India in two days.',source:'Economic Times',pubDate:'2026-08-17'},
 {title:'Vishwanath and Sons Day 2 collection report',movieTitle:'Vishwanath and Sons',amount:'₹22.25 Cr India (Day 2)',verdict:'Source-reported: 45% growth',url:'https://timesofindia.indiatimes.com/entertainment/tamil/movies/news/vishwanath-and-sons-vs-jana-nayagan-box-office-collections-suriyas-film-grows-45-on-day-2-vijays-film-earns-rs-196-15-crore-in-24-days/articleshow/133268575.cms',description:'The film is reported to have grown 45% on Day 2.',source:'Times of India',pubDate:'2026-08-17'},
 {title:'Korean Kanakaraju crosses ₹25 crore worldwide',movieTitle:'Korean Kanakaraju',amount:'₹25+ Cr worldwide (Day 6)',verdict:'Source-reported: Steady run',url:'https://timesofindia.indiatimes.com/entertainment/telugu/movies/box-office/korean-kanakaraju-box-office-collection-day-6-varun-tejs-horror-comedy-maintains-pace-surpasses-rs-25-crore-worldwide/articleshow/133195957.cms',description:'The Telugu horror comedy is reported to have surpassed ₹25 crore worldwide by Day 6.',source:'Times of India',pubDate:'2026-08-16'},
 {title:'Spider-Man: Brand New Day Day 17 box-office report',movieTitle:'Spider-Man: Brand New Day',amount:'Day 17 collection report',verdict:'Source-reported: Steady theatrical run',url:'https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/box-office/spider-man-brand-new-day-box-office-collection-day-17-tom-holland-starrer-sees-big-jump-on-third-saturday-still-lags-behind-massive-awarapan-2-earnings/articleshow/133268642.cms',description:'The film saw a jump on its third Saturday while continuing its theatrical run.',source:'Times of India',pubDate:'2026-08-17'},
 {title:'Batwara 1947 opens with ₹5 crore in India',movieTitle:'Batwara 1947',amount:'₹5 Cr India (Day 1)',verdict:'Source-reported: Decent opening',url:'https://m.economictimes.com/magazines/panache/batwara-1947-box-office-collection-day-1-sunny-deol-preity-zintas-movie-opens-on-a-decent-note-on-independence-day-earns-rs-5-crore-in-india/articleshow/133253633.cms',description:'The Sunny Deol and Preity Zinta starrer opened to a reported ₹5 crore in India.',source:'Economic Times',pubDate:'2026-08-16'}
];
const decode=v=>String(v||'').replace(/<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const strip=v=>decode(String(v||'').replace(/<[^>]+>/g,' ')).replace(/\\s+/g,' ').trim();
const tag=(b,n)=>{const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)</${n}>`,'i'));return m?strip(m[1]):''};
function parse(xml,movie=''){return [...xml.matchAll(/<item>([\\s\\S]*?)<\\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),url:tag(b,'link'),description:strip(tag(b,'description')),pubDate:tag(b,'pubDate'),source:tag(b,'source'),movieTitle:movie})).filter(x=>x.title&&x.url)}
const entertainment=/movie|movies|film|films|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime video|jiohotstar|hotstar|zee5|sony liv|series|web series|box office|theatrical|release|director|producer|song|music|singer|album|episode|season|fans|viral|gossip|rumou?r|dating|relationship|marriage|breakup|engagement|wedding|feud/i;
const nonEntertainment=/football|soccer|cricket|tennis|psg|playstation|sports|election|politics|minister|parliament|weather|rain forecast|stock market|share price|gold price|fuel price|bank|hospital|disease|crime|police|exam result/i;
function keep(x){const s=`${x.title} ${x.description} ${x.source}`;return entertainment.test(s)&&!nonEntertainment.test(s)}
function classify(x){const s=`${x.title} ${x.description}`;if(/official|confirmed|announced|statement|revealed|released/i.test(s))return'confirmed';if(/rumou?r|reportedly|speculation|dating|relationship|marriage|breakup|engagement|spotted|affair|feud/i.test(s))return'rumour';if(/viral|meme|internet|social media|instagram|youtube|reaction|views|fans/i.test(s))return'viral';return'explained'}
function amount(text){const s=String(text||'');const m=s.match(/(?:₹|rs\\.?|inr)\\s?[\\d,.]+\\s?(?:crore|cr|lakh|million)?/i)||s.match(/[\\d,.]+\\s?(?:crore|cr|lakh)\\s?(?:worldwide|ww|india|net)?/i);return m?m[0].replace(/\\s+/g,' ').trim():''}
function verdict(text){const s=String(text||'').toLowerCase();if(/blockbuster|all[- ]time blockbuster/.test(s))return'Source-reported: Blockbuster';if(/super hit|superhit/.test(s))return'Source-reported: Super Hit';if(/\\bhit\\b/.test(s))return'Source-reported: Hit';if(/success|successful|successful run/.test(s))return'Source-reported: Success';if(/average/.test(s))return'Source-reported: Average';if(/flop|disaster/.test(s))return'Source-reported: '+(s.includes('disaster')?'Disaster':'Flop');return'Collection report'}
async function fetchQuery(q,movie=''){const url=`${BASE}?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`;const r=await fetch(url,{headers:HEADERS});if(!r.ok)throw new Error(`News RSS ${r.status}`);return parse(await r.text(),movie)}
function dedupe(items){const seen=new Set();return items.filter(x=>{const key=(x.url||x.title).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>new Date(b.pubDate||0)-new Date(a.pubDate||0))}
function aliasesFor(movie){if(movie==='Korean Kanakaraju')return['Korean Kanakaraju','Kanakaraju'];if(movie==='Vishwanath and Sons')return['Vishwanath and Sons','Vishwanath & Sons','Vishwanath And Sons'];if(movie==='Magudam')return['Magudam','Makutam'];return[movie]}
async function boxOfficeForMovie(movie){const queries=aliasesFor(movie).flatMap(name=>[`"${name}" box office collections`,`"${name}" box office collection`,`"${name}" box office verdict`,`"${name}" theatrical collections`]);const batches=await Promise.allSettled(queries.map(q=>fetchQuery(q,movie)));return dedupe(batches.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(keep)).map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}))}
function fallbackFor(q){const needle=String(q||'').toLowerCase();return FALLBACK_BOX.filter(x=>!needle||x.movieTitle.toLowerCase().includes(needle)||needle.includes('kanakaraju')&&x.movieTitle==='Korean Kanakaraju'||needle.includes('awarapan')&&x.movieTitle==='Awarapan 2'||needle.includes('vishwanath')&&x.movieTitle==='Vishwanath and Sons'||needle.includes('batwara')&&x.movieTitle==='Batwara 1947')}
async function boxOfficeTrending(){const batches=await Promise.allSettled(DEFAULT_BOXOFFICE_MOVIES.map(boxOfficeForMovie));let items=dedupe(batches.flatMap(x=>x.status==='fulfilled'?x.value:[]));items=items.concat(FALLBACK_BOX.filter(f=>!items.some(x=>x.url===f.url)));const reported=DEFAULT_BOXOFFICE_MOVIES.filter(movie=>items.some(x=>x.movieTitle===movie));const discovered=items.map(x=>x.movieTitle).filter(Boolean).filter(movie=>!reported.includes(movie));return {trendingMovies:[...reported,...discovered,...DEFAULT_BOXOFFICE_MOVIES.filter(movie=>!reported.includes(movie)&&!discovered.includes(movie))].slice(0,8),items:items.slice(0,30)}}
export async function onRequestGet({request}){const u=new URL(request.url);const type=u.searchParams.get('type')||'news';const q=u.searchParams.get('q')?.trim()||'';
 if(type==='boxoffice_trending'){try{const data=await boxOfficeTrending();return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),...data}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}catch(e){return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:DEFAULT_BOXOFFICE_MOVIES,items:FALLBACK_BOX.slice(0,8),error:'Live box-office sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}}
 let queries=NEWS_QUERIES;if(type==='boxoffice'){const names=q?[q,...(q.toLowerCase().includes('kanakaraju')?['Korean Kanakaraju']:[])]:DEFAULT_BOXOFFICE_MOVIES;queries=names.flatMap(name=>aliasesFor(name).flatMap(alias=>[`"${alias}" box office collections`,`"${alias}" box office collection`,`"${alias}" box office verdict`,`"${alias}" theatrical collections`]))}
 if(type==='gossip')queries=['Indian celebrity gossip rumours today','Tollywood gossip rumours today','Bollywood celebrity gossip today','South Indian cinema gossip today'];if(type==='ott')queries=['new OTT releases India today movies series','Netflix Prime Video JioHotstar new releases India','Indian movies streaming this week'];
 try{const batches=await Promise.all(queries.map(qry=>fetchQuery(qry,q)));let items=dedupe(batches.flat().filter(keep));if(type==='gossip')items=items.filter(x=>classify(x)==='rumour'||/gossip|rumou?r|dating|relationship|marriage|breakup|feud/i.test(`${x.title} ${x.description}`));if(type==='boxoffice')items=items.map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}));if(type==='boxoffice'&&!items.length)items=fallbackFor(q);return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:type==='boxoffice'?DEFAULT_BOXOFFICE_MOVIES:[],items:items.slice(0,30)}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}catch(e){const fallback=type==='boxoffice'?fallbackFor(q):[];return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:type==='boxoffice'?DEFAULT_BOXOFFICE_MOVIES:[],items:fallback,error:'Live entertainment sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}}
