const BASE='https://news.google.com/rss/search';
const HEADERS={accept:'application/rss+xml, application/xml, text/xml'};
const NEWS_QUERIES=['Indian cinema movie Telugu Bollywood Tamil Malayalam Kannada Hollywood','Tollywood Telugu movie news actor actress trailer release','Bollywood movie news actor actress trailer release','Indian celebrity entertainment gossip rumour relationship movie','OTT Netflix Prime Video JioHotstar Zee5 SonyLIV Indian movies series','Indian movie box office collections Telugu Bollywood Tamil Malayalam Kannada'];
const DEFAULT_BOXOFFICE_MOVIES=['Awarapan 2','Vishwanath and Sons','Batwara 1947','Korean Kanakaraju','Spider-Man: Brand New Day','Thudakkam','Magudam','DC'];
const decode=v=>String(v||'').replace(/<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const strip=v=>decode(String(v||'').replace(/<[^>]+>/g,' ')).replace(/\\s+/g,' ').trim();
const tag=(b,n)=>{const m=b.match(new RegExp(`<${n}(?:\\\\s[^>]*)?>([\\s\\S]*?)</${n}>`,'i'));return m?strip(m[1]):''};
function parse(xml,movie=''){return [...xml.matchAll(/<item>([\\s\\S]*?)<\\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),url:tag(b,'link'),description:strip(tag(b,'description')),pubDate:tag(b,'pubDate'),source:tag(b,'source'),movieTitle:movie})).filter(x=>x.title&&x.url)}
const entertainment=/movie|movies|film|films|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime video|jiohotstar|hotstar|zee5|sony liv|series|web series|box office|theatrical|release|director|producer|song|music|singer|album|episode|season|fans|viral|gossip|rumou?r|dating|relationship|marriage|breakup|engagement|wedding|feud/i;
const nonEntertainment=/football|soccer|cricket|tennis|psg|playstation|sports|election|politics|minister|parliament|weather|rain forecast|stock market|share price|gold price|fuel price|bank|hospital|disease|crime|police|exam result/i;
function keep(x){const s=`${x.title} ${x.description} ${x.source}`;return entertainment.test(s)&&!nonEntertainment.test(s)}
function classify(x){const s=`${x.title} ${x.description}`;if(/official|confirmed|announced|statement|revealed|released/i.test(s))return'confirmed';if(/rumou?r|reportedly|speculation|dating|relationship|marriage|breakup|engagement|spotted|affair|feud/i.test(s))return'rumour';if(/viral|meme|internet|social media|instagram|youtube|reaction|views|fans/i.test(s))return'viral';return'explained'}
function amount(text){const s=String(text||'');const m=s.match(/(?:₹|rs\\.?|inr)\\s?[\\d,.]+\\s?(?:crore|cr|lakh|million)?/i)||s.match(/[\\d,.]+\\s?(?:crore|cr|lakh)\\s?(?:worldwide|ww|india|net)?/i);return m?m[0].replace(/\\s+/g,' ').trim():''}
function verdict(text){const s=String(text||'').toLowerCase();if(/blockbuster|all[- ]time blockbuster/.test(s))return'Source-reported: Blockbuster';if(/super hit|superhit/.test(s))return'Source-reported: Super Hit';if(/\\bhit\\b/.test(s))return'Source-reported: Hit';if(/success|successful|successful run/.test(s))return'Source-reported: Success';if(/average/.test(s))return'Source-reported: Average';if(/flop|disaster/.test(s))return'Source-reported: '+(s.includes('disaster')?'Disaster':'Flop');return'Collection report'}
async function fetchQuery(q,movie=''){const url=`${BASE}?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`;const r=await fetch(url,{headers:HEADERS});if(!r.ok)throw new Error(`News RSS ${r.status}`);return parse(await r.text(),movie)}
function dedupe(items){const seen=new Set();return items.filter(x=>{const key=(x.url||x.title).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>new Date(b.pubDate||0)-new Date(a.pubDate||0))}
async function boxOfficeForMovie(movie){const aliases=movie==='Korean Kanakaraju'?['Korean Kanakaraju','Kanakaraju']: [movie];const queries=aliases.flatMap(name=>[`"${name}" box office collections`,`"${name}" box office collection`,`"${name}" box office verdict`,`"${name}" theatrical collections`]);const batches=await Promise.allSettled(queries.map(q=>fetchQuery(q,movie)));return dedupe(batches.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(keep)).map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}))}
async function boxOfficeTrending(){const batches=await Promise.allSettled(DEFAULT_BOXOFFICE_MOVIES.map(boxOfficeForMovie));let items=dedupe(batches.flatMap(x=>x.status==='fulfilled'?x.value:[]));if(items.length<4){const extra=await Promise.allSettled(['Indian movie box office collections today','South Indian movie box office collections today','Bollywood movie box office collections today'].map(q=>fetchQuery(q)));items=dedupe(items.concat(extra.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(keep).map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}))));}const trendingMovies=[];for(const movie of DEFAULT_BOXOFFICE_MOVIES){if(items.some(x=>x.movieTitle===movie)){trendingMovies.push(movie)}}for(const x of items){if(x.movieTitle&&!trendingMovies.includes(x.movieTitle))trendingMovies.push(x.movieTitle)}return {trendingMovies:trendingMovies.slice(0,8),items:items.slice(0,30)}}
export async function onRequestGet({request}){const u=new URL(request.url);const type=u.searchParams.get('type')||'news';const q=u.searchParams.get('q')?.trim()||'';if(type==='boxoffice_trending'){try{const data=await boxOfficeTrending();return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),...data}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}catch(e){return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:DEFAULT_BOXOFFICE_MOVIES,items:[],error:'Live box-office sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}}let queries=NEWS_QUERIES;if(type==='boxoffice'){const names=q?[q,...(q.toLowerCase().includes('kanakaraju')?['Korean Kanakaraju']:[])]:DEFAULT_BOXOFFICE_MOVIES;queries=names.flatMap(name=>[`"${name}" box office collections`,`"${name}" box office collection`,`"${name}" box office verdict`,`"${name}" theatrical collections`]);}if(type==='gossip')queries=['Indian celebrity gossip rumours today','Tollywood gossip rumours today','Bollywood celebrity gossip today','South Indian cinema gossip today'];if(type==='ott')queries=['new OTT releases India today movies series','Netflix Prime Video JioHotstar new releases India','Indian movies streaming this week'];try{const batches=await Promise.all(queries.map(qry=>fetchQuery(qry,q)));let items=dedupe(batches.flat().filter(keep));if(type==='gossip')items=items.filter(x=>classify(x)==='rumour'||/gossip|rumou?r|dating|relationship|marriage|breakup|feud/i.test(`${x.title} ${x.description}`));if(type==='boxoffice')items=items.map(x=>({...x,amount:amount(`${x.title} ${x.description}`),verdict:verdict(`${x.title} ${x.description}`)}));return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:type==='boxoffice'?DEFAULT_BOXOFFICE_MOVIES:[],items:items.slice(0,30)}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}catch(e){return new Response(JSON.stringify({type,q,fetchedAt:new Date().toISOString(),trendingMovies:type==='boxoffice'?DEFAULT_BOXOFFICE_MOVIES:[],items:[],error:'Live entertainment sources are temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=120'}})}}
