const BASE='https://news.google.com/rss/search';
const HEADERS={accept:'application/rss+xml, application/xml, text/xml'};
const QUERIES=['Indian cinema Telugu Bollywood Tamil Malayalam Kannada Hollywood news today','Tollywood Telugu movie news today','Bollywood movie news today','Indian celebrity entertainment gossip today','South Indian cinema viral today','Telugu box office today','Bollywood box office today','new movie releases India today','OTT releases India August 2026'];
const BAD=/football|soccer|cricket|tennis|psg|playstation|sports|election|politics|minister|parliament|weather|rain forecast|stock market|share price|gold price|fuel price|bank|hospital|disease|crime|police|exam result/i;
const GOOD=/movie|film|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime|jiohotstar|zee5|series|box office|release|director|producer|song|music|viral|gossip|rumou?r|fans|social media|streaming/i;
const strip=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(b,n)=>{const m=b.match(new RegExp(`<${n}(?:\s[^>]*)?>([\s\S]*?)</${n}>`,'i'));return m?strip(m[1]):''};
const parse=xml=>[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),url:tag(b,'link'),description:tag(b,'description'),pubDate:tag(b,'pubDate'),source:tag(b,'source')})).filter(x=>x.title&&x.url);
const valid=x=>{const s=`${x.title} ${x.description} ${x.source}`;return GOOD.test(s)&&!BAD.test(s)};
async function get(q){const u=`${BASE}?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`;const r=await fetch(u,{headers:HEADERS});if(!r.ok)throw new Error(String(r.status));return parse(await r.text())}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.url||x.title;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(b.pubDate||0)-new Date(a.pubDate||0))}
const fallbackNews=[
 {title:'Vishwanath and Sons crosses ₹100 crore worldwide in two days',source:'Times of India',url:'https://timesofindia.indiatimes.com/entertainment/tamil/movies/news/suriya-and-mamitha-baiju-starrer-vishwanath-and-sons-crosses-rs-100-crore-worldwide-in-just-two-days/articleshow/133274258.cms',description:'Suriya and Mamitha Baiju starrer crosses the ₹100 crore worldwide milestone in two days.',pubDate:'2026-08-17'},
 {title:'Awarapan 2 enters the ₹50 crore India club in two days',source:'Economic Times',url:'https://m.economictimes.com/magazines/panache/awarapan-2-box-office-collection-day-2-emraan-hashmis-sequel-beats-batwara-1947-enters-rs-50-crore-club-in-india-awarapan-3-update/articleshow/133268852.cms',description:'Awarapan 2 posts a strong opening and crosses ₹50 crore in India in two days.',pubDate:'2026-08-17'},
 {title:'I, Nobody OTT release date announced for JioHotstar',source:'Indian Express Malayalam',url:'https://malayalam.indianexpress.com/entertainment/i-nobody-ott-release-date-prithviraj-movie-jio-hotstar-12265448',description:'Prithviraj Sukumaran starrer I, Nobody is set to stream on JioHotstar from August 25.',pubDate:'2026-08-17'},
 {title:'Cocktail 2 OTT release sparks fresh online debate',source:'Times of India',url:'https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/cocktail-2-ott-release-sparks-debate-and-garners-mixed-reviews-netizens-call-shahid-kapoor-kriti-sanon-and-rashmika-mandanna-starrer-a-rage-bait/articleshow/133267514.cms',description:'Cocktail 2 is generating renewed online discussion after its OTT release.',pubDate:'2026-08-16'}
];
export async function onRequestGet(){const results=await Promise.allSettled(QUERIES.map(get));const items=dedupe(results.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(valid));const news=items.filter(x=>!/(gossip|rumou?r|dating|relationship|breakup|affair|feud)/i.test(`${x.title} ${x.description}`)).slice(0,8);const buzz=items.filter(x=>/(gossip|rumou?r|dating|relationship|breakup|affair|feud|spotted)/i.test(`${x.title} ${x.description}`)).slice(0,8);const viral=items.filter(x=>/(viral|social media|instagram|youtube|reaction|views|fans|meme|debate)/i.test(`${x.title} ${x.description}`)).slice(0,8);const safeNews=news.length?news:fallbackNews;return new Response(JSON.stringify({fetchedAt:new Date().toISOString(),news:safeNews,buzz,viral,available:items.length>0}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}
