const BASE='https://news.google.com/rss/search';
const HEADERS={accept:'application/rss+xml, application/xml, text/xml'};
const QUERIES=['Indian cinema Telugu Bollywood Tamil Malayalam Kannada Hollywood news today','Tollywood Telugu movie news today','Bollywood movie news today','Indian celebrity entertainment gossip today','South Indian cinema viral today','Telugu box office today','Bollywood box office today','new movie releases India today'];
const BAD=/football|soccer|cricket|tennis|psg|playstation|sports|election|politics|minister|parliament|weather|rain forecast|stock market|share price|gold price|fuel price|bank|hospital|disease|crime|police|exam result/i;
const GOOD=/movie|film|cinema|tollywood|bollywood|kollywood|mollywood|sandalwood|hollywood|actor|actress|celebrity|star|trailer|teaser|ott|netflix|prime|jiohotstar|zee5|series|box office|release|director|producer|song|music|viral|gossip|rumou?r|fans|social media/i;
const strip=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const tag=(b,n)=>{const m=b.match(new RegExp(`<${n}(?:\s[^>]*)?>([\s\S]*?)</${n}>`,'i'));return m?strip(m[1]):''};
const parse=xml=>[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),url:tag(b,'link'),description:tag(b,'description'),pubDate:tag(b,'pubDate'),source:tag(b,'source')})).filter(x=>x.title&&x.url);
const valid=x=>{const s=`${x.title} ${x.description} ${x.source}`;return GOOD.test(s)&&!BAD.test(s)};
async function get(q){const u=`${BASE}?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`;const r=await fetch(u,{headers:HEADERS});if(!r.ok)throw new Error(String(r.status));return parse(await r.text())}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.url||x.title;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(b.pubDate||0)-new Date(a.pubDate||0))}
const fallbackNews=[
 {title:'Korean Kanakaraju box office and latest Telugu cinema updates',source:'MovieBlog watchlist',url:'https://movie-blog-bdt.pages.dev/pages/box-office-live',description:'Current Telugu theatrical and box-office coverage is being tracked by MovieBlog.',pubDate:new Date().toISOString()},
 {title:'Awarapan 2 and current Indian box-office updates',source:'MovieBlog watchlist',url:'https://movie-blog-bdt.pages.dev/pages/box-office-live',description:'Latest theatrical performance reports are being monitored across Indian cinema.',pubDate:new Date().toISOString()}
];
export async function onRequestGet(){const results=await Promise.allSettled(QUERIES.map(get));const items=dedupe(results.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(valid));const news=items.filter(x=>!/(gossip|rumou?r|dating|relationship|breakup|affair|feud)/i.test(`${x.title} ${x.description}`)).slice(0,8);const buzz=items.filter(x=>/(gossip|rumou?r|dating|relationship|breakup|affair|feud|spotted)/i.test(`${x.title} ${x.description}`)).slice(0,8);const viral=items.filter(x=>/(viral|social media|instagram|youtube|reaction|views|fans|meme)/i.test(`${x.title} ${x.description}`)).slice(0,8);const safeNews=news.length?news:fallbackNews;return new Response(JSON.stringify({fetchedAt:new Date().toISOString(),news:safeNews,buzz,viral,available:items.length>0}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300, s-maxage=300'}})}
