const RSS_URL='https://trends.google.com/trending/rss?geo=IN';
const TRENDS_WEB_URL='https://trends.google.com/trending?geo=IN';
const TERMS=['movie','movies','film','films','cinema','trailer','teaser','actor','actress','celebrity','celebrities','ott','netflix','prime video','jiohotstar','hotstar','zee5','sony liv','series','web series','song','singer','music','bollywood','tollywood','kollywood','mollywood','hollywood','tv show','television','review','box office','release date','cast','director','producer','episode','season','streaming','theatrical','marvel','dc comics','superhero','anime','k-pop','kpop'];
const NEGATIVE=['football','soccer','cricket','tennis','psg','lens vs','playstation','sports','olympics','formula 1','f1','nba','nfl','election','politics','minister','parliament','court','police','crime','weather','rain forecast','medical','disease','hospital','fuel price','gold price','share price','stock market','inflation','bank','investment','road construction','highway','bus accident','ration card','e-kyc','exam result'];
const decode=v=>v.replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"').replaceAll('&#39;',"'");
function tag(b,n){const m=b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)</${n}>`,'i'));return m?decode(m[1].trim()):''}
function all(b,n){return [...b.matchAll(new RegExp(`<${n}[^>]*>([\\s\\S]*?)</${n}>`,'gi'))].map(m=>decode(m[1].trim())).filter(Boolean)}
function parse(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]).map(b=>({title:tag(b,'title'),traffic:tag(b,'ht:approx_traffic'),description:tag(b,'description'),pubDate:tag(b,'pubDate'),newsTitles:all(b,'ht:news_item_title'),newsUrls:all(b,'ht:news_item_url'),newsSources:all(b,'ht:news_item_source')})).filter(x=>x.title)}
function relevance(x){const s=[x.title,x.description,...x.newsTitles,...x.newsSources].join(' ').toLowerCase();if(NEGATIVE.some(t=>s.includes(t)))return'low';const hits=TERMS.filter(t=>s.includes(t)).length;return hits>=2?'high':hits===1?'medium':'low'}
function score(x){const r=relevance(x);const base=r==='high'?55:r==='medium'?30:0;const t=String(x.traffic||'').toLowerCase();let traffic=6;if(/500k|1m|10l/.test(t))traffic=35;else if(/200k|100k|5l/.test(t))traffic=28;else if(/50k|20k|2l/.test(t))traffic=20;else if(/10k|1l/.test(t))traffic=12;else if(/5k|2k|1k/.test(t))traffic=10;return Math.min(100,base+traffic+Math.min(10,(x.newsTitles?.length||0)*2)+10)}
export async function onRequestGet(){try{const r=await fetch(RSS_URL,{headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)throw new Error(`Google Trends returned ${r.status}`);const xml=await r.text();const trends=parse(xml).map(x=>({...x,relevance:relevance(x),score:score(x),openUrl:x.newsUrls?.[0]||TRENDS_WEB_URL})).filter(x=>x.relevance!=='low').sort((a,b)=>b.score-a.score);return new Response(JSON.stringify({source:'Google Trends Trending Now RSS',geo:'IN',fetchedAt:new Date().toISOString(),trends}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=600, s-maxage=600'}})}catch(e){return new Response(JSON.stringify({source:'Google Trends Trending Now RSS',geo:'IN',fetchedAt:new Date().toISOString(),trends:[],error:'Trending data is temporarily unavailable.'}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300'}})}}
